### ISSUE TITLE
Expected Table-like input error when creating an altair chart

### ISSUE THREAD

**Issue by samesand** [vega/vegafusion#559]
Altair 5.5.0
VegaFusion 2.0.1

I'm trying to create charts using the vegafusion transformer, but I get the following error:
TypeError: Expected Table-like input or dict of arrays or sequence of arrays.

This code generates the error:
`import pandas as pd`
`import altair as alt`
`chart_data = pd.DataFrame([1,2,3,4,5],columns=['y'])`
`alt.Chart(chart_data).mark_bar().encode(y='y')`

I have a different computer with the same versions of Python, Altair and VegaFusion where this code works.

So far, I have tried to uninstall and reinstall Altair, VegaFusion and Python without success.

**Comment by MarcoGorelli** [comment]
Hi can you show the full error message please

**Comment by samesand** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\vegafusion\runtime.py:326, in VegaFusionRuntime._import_inline_datasets(self, inline_datasets, inline_dataset_usage)
    [324](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:324)         df_nw = df_nw.select(columns)
--> [326](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:326)     imported_inline_datasets[name] = Table(df_nw)  # type: ignore[arg-type]
    [327](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:327) except TypeError:
    [328](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:328)     # Not supported by Narwhals, try pycapsule interface directly

TypeError: Expected Table-like input or dict of arrays or sequence of arrays.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python313\site-packages\IPython\core\formatters.py:1036, in MimeBundleFormatter.__call__(self, obj, include, exclude)
   [1033](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/e193645/OneDrive%20-%20Applied%20Materials/Training/Python/Python%20Class/~/AppData/Roaming/Python/Python313/site-packages/IPython/core/formatters.py:1033)     method = get_real_method(obj, self.print_method)
   [1035](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/e193645/OneDrive%20-%20Applied%20Materials/Training/Python/Python%20Class/~/AppData/Roaming/Python/Python313/site-packages/IPython/core/formatters.py:1035)     if method is not None:
-> [1036](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/e193645/OneDrive%20-%20Applied%20Materials/Training/Python/Python%20Class/~/AppData/Roaming/Python/Python313/site-packages/IPython/core/formatters.py:1036)         return method(include=include, exclude=exclude)
   [1037](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/e193645/OneDrive%20-%20Applied%20Materials/Training/Python/Python%20Class/~/AppData/Roaming/Python/Python313/site-packages/IPython/core/formatters.py:1037)     return None
   [1038](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/e193645/OneDrive%20-%20Applied%20Materials/Training/Python/Python%20Class/~/AppData/Roaming/Python/Python313/site-packages/IPython/core/formatters.py:1038) else:

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\altair\vegalite\v5\api.py:3682, in TopLevelMixin._repr_mimebundle_(self, *args, **kwds)
   [3680](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/vegalite/v5/api.py:3680) else:
   [3681](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/vegalite/v5/api.py:3681)     if renderer := renderers.get():
-> [3682](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/vegalite/v5/api.py:3682)         return renderer(dct)

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\altair\utils\display.py:232, in HTMLRenderer.__call__(self, spec, **metadata)
    [230](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/display.py:230) kwargs = self.kwargs.copy()
    [231](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/display.py:231) kwargs.update(**metadata, output_div=self.output_div)
--> [232](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/display.py:232) return spec_to_mimebundle(spec, format="html", **kwargs)

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\altair\utils\mimebundle.py:129, in spec_to_mimebundle(spec, format, mode, vega_version, vegaembed_version, vegalite_version, embed_options, engine, **kwargs)
    [127](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/mimebundle.py:127) internal_mode: Literal["vega-lite", "vega"] = mode
    [128](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/mimebundle.py:128) if using_vegafusion():
--> [129](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/mimebundle.py:129)     spec = compile_with_vegafusion(spec)
    [130](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/mimebundle.py:130)     internal_mode = "vega"
    [132](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/mimebundle.py:132) # Default to the embed options set by alt.renderers.set_embed_options

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\altair\utils\_vegafusion_data.py:273, in compile_with_vegafusion(vegalite_spec)
    [271](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:271) # Pre-evaluate transforms in vega spec with vegafusion
    [272](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:272) row_limit = data_transformers.options.get("max_rows", None)
--> [273](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:273) transformed_vega_spec, warnings = vf.runtime.pre_transform_spec(
    [274](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:274)     vega_spec,
    [275](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:275)     vf.get_local_tz(),
    [276](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:276)     inline_datasets=inline_tables,
    [277](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:277)     row_limit=row_limit,
    [278](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:278) )
    [280](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:280) # Check from row limit warning and convert to MaxRowsError
    [281](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/altair/utils/_vegafusion_data.py:281) handle_row_limit_exceeded(row_limit, warnings)

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\vegafusion\runtime.py:408, in VegaFusionRuntime.pre_transform_spec(self, spec, local_tz, default_input_tz, row_limit, preserve_interactivity, inline_datasets, keep_signals, keep_datasets)
    [347](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:347) """
    [348](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:348) Evaluate supported transforms in an input Vega specification
    [349](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:349) 
   (...)
    [405](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:405)         were eligible for pre-transforming
    [406](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:406) """
    [407](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:407) local_tz = local_tz or get_local_tz()
--> [408](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:408) imported_inline_dataset = self._import_inline_datasets(
    [409](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:409)     inline_datasets, get_inline_column_usage(spec)
    [410](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:410) )
    [412](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:412) new_spec, warnings = self.runtime.pre_transform_spec(
    [413](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:413)     spec,
    [414](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:414)     local_tz=local_tz,
   (...)
    [420](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:420)     keep_datasets=parse_variables(keep_datasets),
    [421](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:421) )
    [423](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:423) return new_spec, warnings

File c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\vegafusion\runtime.py:330, in VegaFusionRuntime._import_inline_datasets(self, inline_datasets, inline_dataset_usage)
    [327](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:327) except TypeError:
    [328](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:328)     # Not supported by Narwhals, try pycapsule interface directly
    [329](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:329)     if hasattr(value, "__arrow_c_stream__"):
--> [330](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:330)         imported_inline_datasets[name] = Table(value)  # type: ignore[arg-type]
    [331](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:331)     else:
    [332](file:///C:/Users/e193645/AppData/Local/Programs/Python/Python313/Lib/site-packages/vegafusion/runtime.py:332)         raise

TypeError: Expected Table-like input or dict of arrays or sequence of arrays.

**Comment by MarcoGorelli** [comment]
ah thanks - this'll be fixed by https://github.com/vega/vegafusion/pull/560

**Comment by yuliap924** [comment]
I still have this issue. It happens after I run alt.data_transformers.enable("vegafusion"):
`import numpy as np
import pandas as pd
import altair as alt

alt.data_transformers.enable("vegafusion")
rand = np.random.RandomState(0)
data = pd.DataFrame({'value': rand.randn(100).cumsum()},
                    index=pd.date_range('2018', freq='D', periods=100))
alt.Chart(data.reset_index()).mark_line().encode(
    x='index:T',
    y='value:Q'
)`

**Comment by jonmmease** [comment]
Hi @yuliap924, are you on version 2.0.2?

**Comment by samesand** [comment]
@MarcoGorelli Hello, could you tell me if this is a different issue than the one in #560 ?

**Comment by samesand** [comment]
Here is the output:

c:\Users\e193645\AppData\Local\Programs\Python\Python313\python.exe
c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\sitepackages\pandas\__init__.py
2.2.3
c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\sitepackages\altair\__init__.py
5.5.0
c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\sitepackages\narwhals\__init__.py
1.23.0
c:\Users\e193645\AppData\Local\Programs\Python\Python313\Lib\site-packages\vegafusion\__init__.py
2.0.2

**Comment by MarcoGorelli** [comment]
thanks

not sure to be honest - if you make a new virtual environment and install you dependencies afresh in there, does it work?

**Comment by samesand** [comment]
I tried using a venv and I still get the same error:

TypeError                                 Traceback (most recent call last)File c:\Users\e1935\OneDrive\Testing2\.venv\Lib\site-packages\vegafusion\runtime.py:326, in VegaFusionRuntime._import_inline_datasets(self, inline_datasets, inline_dataset_usage)    324         df_nw = df_nw.select(columns)--> 326     imported_inline_datasets[name] = Table(df_nw)  # type: ignore[arg-type]    327 except TypeError:    328     # Not supported by Narwhals, try pycapsule interface directly  TypeError: Expected Table-like input or dict of arrays or sequence of arrays. During handling of the above exception, another exception occurred: TypeError                                 Traceback (most recent call last)File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\IPython\core\formatters.py:1036, in MimeBundleFormatter.__call__(self, obj, include, exclude)   1033     method = get_real_method(obj, self.print_method)   1035     if method is not None:-> 1036         return method(include=include, exclude=exclude)   1037     return None   1038 else: File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\altair\vegalite\v5\api.py:3682, in TopLevelMixin._repr_mimebundle_(self, *args, **kwds)   3680 else:   3681     if renderer := renderers.get():-> 3682         return renderer(dct) File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\altair\utils\display.py:232, in HTMLRenderer.__call__(self, spec, **metadata)    230 kwargs = self.kwargs.copy()    231 kwargs.update(**metadata, output_div=self.output_div)--> 232 return spec_to_mimebundle(spec, format="html", **kwargs) File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\altair\utils\mimebundle.py:129, in spec_to_mimebundle(spec, format, mode, vega_version, vegaembed_version, vegalite_version, embed_options, engine, **kwargs)    127 internal_mode: Literal["vega-lite", "vega"] = mode    128 if using_vegafusion():--> 129     spec = compile_with_vegafusion(spec)    130     internal_mode = "vega"    132 # Default to the embed options set by alt.renderers.set_embed_options  File c:\Users\e1935\OneDrive\Testing2\.venv\Lib\site-packages\altair\utils\_vegafusion_data.py:273, in compile_with_vegafusion(vegalite_spec)    271 # Pre-evaluate transforms in vega spec with vegafusion    272 row_limit = data_transformers.options.get("max_rows", None)--> 273 transformed_vega_spec, warnings = vf.runtime.pre_transform_spec(    274     vega_spec,    275     vf.get_local_tz(),    276     inline_datasets=inline_tables,    277     row_limit=row_limit,    278 )    280 # Check from row limit warning and convert to MaxRowsError    281 handle_row_limit_exceeded(row_limit, warnings) File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\vegafusion\runtime.py:408, in VegaFusionRuntime.pre_transform_spec(self, spec, local_tz, default_input_tz, row_limit, preserve_interactivity, inline_datasets, keep_signals, keep_datasets)    347 """    348 Evaluate supported transforms in an input Vega specification    349   (...)    405         were eligible for pre-transforming    406 """    407 local_tz = local_tz or get_local_tz()--> 408 imported_inline_dataset = self._import_inline_datasets(    409     inline_datasets, get_inline_column_usage(spec)    410 )    412 new_spec, warnings = self.runtime.pre_transform_spec(    413     spec,    414     local_tz=local_tz,   (...)    420     keep_datasets=parse_variables(keep_datasets),    421 )    423 return new_spec, warnings File c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\vegafusion\runtime.py:330, in VegaFusionRuntime._import_inline_datasets(self, inline_datasets, inline_dataset_usage)    327 except TypeError:    328     # Not supported by Narwhals, try pycapsule interface directly    329     if hasattr(value, "__arrow_c_stream__"):--> 330         imported_inline_datasets[name] = Table(value)  # type: ignore[arg-type]    331     else:    332         raise  TypeError: Expected Table-like input or dict of arrays or sequence of arrays.

**Comment by MarcoGorelli** [comment]
can you format your code in triple backtricks please, else it's hard/impossible to parse?

**Comment by samesand** [comment]
my apologies, that was the error output. 

This is the code:
`import pandas as pd`
`import altair as alt`
`alt.data_transformers.enable('vegafusion')`
`chart_data = pd.DataFrame([1,2,3,4,5],columns=['y'])`
`alt.Chart(chart_data).mark_bar().encode(y='y')`

**Comment by MarcoGorelli** [comment]
sure, thanks - and the output from https://github.com/vega/vegafusion/issues/559#issuecomment-2753580837 with your virtual environment activate?

also, could you show what happens if you run
```python
from arro3.core import Table
import pandas as pd
import pyarrow as pa

chart_data = pd.DataFrame([1,2,3,4,5],columns=['y'])
Table(chart_data)
```
please?

**Comment by samesand** [comment]
Yes, the error in 559 was with venv active, and a fresh install of altair and vegafusion.

this is the output from your request:

arro3.core.Table
-----------
y: Int64

**Comment by MarcoGorelli** [comment]
ok thanks, so the `arro3.core.Table(df)` part works...

how about
```
from arro3.core import Table
import narwhals as nw
import pandas as pd
import pyarrow as pa

chart_data = pd.DataFrame([1,2,3,4,5],columns=['y'])
df = nw.from_native(chart_data)
print(df)
print(Table(df))
```
?

**Comment by samesand** [comment]
this is the output
┌──────────────────┐
|Narwhals DataFrame|
|------------------|
|          y       |
|       0  1       |
|       1  2       |
|       2  3       |
|       3  4       |
|       4  5       |
└──────────────────┘
arro3.core.Table
-----------

**Comment by MarcoGorelli** [comment]
🤔 looks fine - and the output from https://github.com/vega/vegafusion/issues/559#issuecomment-2753580837 with your venv activated?

**Comment by samesand** [comment]
yes, the venv was activated

**Comment by MarcoGorelli** [comment]
sorry i mean can you post that output again with your venv activated please? when you last posted that output it was without the venv activated

i'm referring to
```
import sys
print(sys.executable)
import pandas
import altair
import narwhals
import vegafusion
print(pandas.__file__)
print(pandas.__version__)
print(altair.__file__)
print(altair.__version__)
print(narwhals.__file__)
print(narwhals.__version__)
print(vegafusion.__file__)
print(vegafusion.__version__)
```

**Comment by samesand** [comment]
yes, sorry that was without venv.

this is the output with the venv activated:

c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Scripts\python.exe
c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\pandas\__init__.py
2.2.3
c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\altair\__init__.py
5.5.0
c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\narwhals\__init__.py
1.33.0
c:\Users\e193645\OneDrive - Applied Materials\Testing2\.venv\Lib\site-packages\vegafusion\__init__.py
2.0.2

One thing that I should have mentioned before. After activating the venv, vegafusion transformer did not work right after the install. It was missing this package: vl-convert-python>=1.6.0, so I installed it manually.

**Comment by rambip** [comment]
I was able to solve the issue by downgrading to `vega==1.6.9`. So I guess it's a regression.
More info here: https://github.com/vega/vegafusion/issues/556#issue-2811819661

**Comment by MarcoGorelli** [comment]
@rambip could you show your code and paste your full traceback please?

I'd really like to fix this but without being able to reproduce it and without clues it's a bit hard to know where to start..

**Comment by rambip** [comment]
Well, I use a virtual environment. So the version is the latest compatible with all the requirements.
I use `uv` to manage my dependencies. I did `uv add pandas altair vega[embed] vegafusion vegafusion-python-embed vl-convert-python`
But for reference, here is my dependency tree:
https://gist.github.com/rambip/71fa35fdf2e1f218c3aa9e28aaee0627

**Comment by MarcoGorelli** [comment]
ah, thanks! if I uninstall pyarrow, then I can also reproduce! ok, nice. looking into this

**Comment by rambip** [comment]
So shouldn't vegafusion 2.0 require pyarrow as a dependency ?
Or the code should call something different than `__arrow_c_stream__` to get the underlying data I guess.

**Comment by MarcoGorelli** [comment]
it's not required for all backends though, e.g. Polars doesn't require it

**Comment by MarcoGorelli** [comment]
Have reported to Arro3 https://github.com/kylebarron/arro3/issues/325

If anyone else stumbles upon this, my suggested solution would be to install pyarrow

**Comment by jonmmease** [comment]
Thanks for digging in @MarcoGorelli!
